# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "modalsupport"
  s.version = "0.9.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Javier Goizueta"]
  s.date = "2012-05-14"
  s.description = "additional support extensions to ActiveSupport and HoboSupport"
  s.email = "jgoizueta@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/modalsupport.rb",
    "lib/modalsupport/array.rb",
    "lib/modalsupport/basic_object.rb",
    "lib/modalsupport/enumerable.rb",
    "lib/modalsupport/file.rb",
    "lib/modalsupport/full.rb",
    "lib/modalsupport/hash.rb",
    "lib/modalsupport/methodcall.rb",
    "lib/modalsupport/mixins/bracket_constructor.rb",
    "lib/modalsupport/mixins/state_equivalent.rb",
    "lib/modalsupport/recursive_map.rb",
    "lib/modalsupport/regexp.rb",
    "lib/modalsupport/ruby_engine.rb",
    "lib/modalsupport/ruby_platform.rb",
    "lib/modalsupport/ruby_version.rb",
    "lib/modalsupport/string.rb",
    "modalsupport.gemspec",
    "test/helper.rb",
    "test/test_array_index.rb",
    "test/test_array_to_h.rb",
    "test/test_bracket_constructor.rb",
    "test/test_build_hash.rb",
    "test/test_cross_each.rb",
    "test/test_grep.rb",
    "test/test_gsub.rb",
    "test/test_map_hash.rb",
    "test/test_map_with_index.rb",
    "test/test_match.rb",
    "test/test_methodcall.rb",
    "test/test_paralell_each.rb",
    "test/test_product.rb",
    "test/test_recursive_map.rb",
    "test/test_relative_path.rb",
    "test/test_rest.rb",
    "test/test_rotate.rb",
    "test/test_slice.rb",
    "test/test_state_equivalent.rb",
    "test/test_unindent.rb",
    "test/test_unwrap.rb"
  ]
  s.homepage = "http://github.com/jgoizueta/modalsupport"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "simple extensions to core classes"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

